name: Lint Markdown

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-markdown:
    uses: L3DigitalNet/project-standards/.github/workflows/lint-markdown.yml@v4.3.0
    with:
      globs: "**/*.md"
